FROM alpine:latest
MAINTAINER duoduo 25574522@qq.com

RUN echo 'http://mirrors.ustc.edu.cn/alpine/edge/main' > /etc/apk/repositories && \
    echo '@community http://mirrors.ustc.edu.cn/alpine/edge/community' >> /etc/apk/repositories && \
    echo '@testing http://mirrors.ustc.edu.cn/alpine/edge/testing' >> /etc/apk/repositories && \
    apk update

RUN apk add \
    curl \
    openssh-client \
    busybox-extras

# timezone
ENV TIMEZONE Asia/Shanghai
RUN apk add tzdata
RUN ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
RUN echo $TIMEZONE > /etc/timezone