FROM registry.cn-beijing.aliyuncs.com/andy320/dev-alpine3.11:v1.0.0
#RUN apk --no-cache add ca-certificates

ADD output/broker /usr/local/bin/
ADD log4rs.yaml /etc/broker/

EXPOSE 9000 9080

ENTRYPOINT ["broker"]