[package]
name = "proto"
version = "0.1.0"
authors = ["Andy320 <25574522@qq.com>"]
edition = "2018"

[dependencies]
prost = "0.6"
prost-derive = "0.6"
tonic = "0.2"

[build-dependencies]
tonic-build = { version = "0.2", features = ["prost"] }