[package]
name = "broker"
version = "0.1.0"
authors = ["Andy320 <25574522@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "broker"
path = "src/bin/broker_main.rs"

[dependencies]
common = { version = "0.1", path = "../common" }